const LOCATIONS = {
  restaurant: "Ресторан",
  spa: "Спа-салон",
  hotel: "Отель",
  terroristBase: "База террористов",
  bank: "Банк",
  hospital: "Больница",
  university: "Университет",
  embassy: "Посольство",
  movieStudio: "Киностудия",
  corporateParty: "Корпоративная вечеринка",
  vegetableMarket: "Овощебаза",
  partisanDetachment: "Партизанский отряд",
  passengerTrain: "Пассажирский поезд",
  pirateShip: "Пиратский корабль",
  polarStation: "Полярная станция",
  supermarket: "Супермаркет",
  theatre: "Театр",
  militaryUnit: "Воинская часть",
  crusaderArmy: "Войско крестоносцев",
  casino: "Казино",
  oceanLiner: "Океанский лайнер",
  orbitalStation: "Орбитальная станция",
  beach: "Пляж",
  submarine: "Подводная лодка",
  policeStation: "Полицейский участок",
  airplane: "Самолёт",
  serviceStations: "Станция техобслуживания",
  church: "Церковь",
  shapitoCircus: "Цирк-шапито",
  school: "Школа",
};

const STATUSES = {
  restaurant: {
    musician: "Музыкант",
    visitors: "Посетитель",
    bouncer: "Вышибала",
    headwaiter: "Метрдотель",
    chef: "Шеф-повар",
    waiter: "Официант",
    critic: "Критик",
  },
  spa: {
    customer: "Клиент",
    stylist: "Стилист",
    masseur: "Массажист",
    visagiste: "Визажист",
    manicurist: "Маникюрщик",
    beautician: "Косметолог",
    dermatologist: "Дерматолог",
  },
  hotel: {
    bartender: "Бармен",
    lodger: "Постоялец",
    housemaid: "Горничная",
    porter: "Швейцар",
    securityGuard: "Охранник",
    manager: "Управляющий",
    porter: "Портье",
  },
  terroristBase: {
    errandBoy: "Мальчик на побегушках",
    cellHead: "Глава ячейки",
    actionMovie: "Боевик",
    suicideBomber: "Смертник",
    medic: "Медик",
    rookie: "Новобранец",
    shepherd: "Пастух",
  },
  bank: {
    customer: "Клиент",
    securityGuard: "Охранник",
    robber: "Грабитель",
    cashier: "Кассир",
    manager: "Управляющий",
    collector: "Инкассатор",
    consultant: "Консультант",
  },
  hospital: {
    therapist: "Терапевт",
    surgeon: "Хирург",
    nurse: "Медсестра",
    patient: "Пациент",
    pathologist: "Патологоанатом",
    headPhysician: "Главврач",
    intern: "Итерн",
  },
  university: {
    student: "Студент",
    watchman: "Вахтёр",
    rector: "Ректор",
    professor: "Профессор",
    graduateStudent: "Аспирант",
    psychologist: "Психолог",
    dean: "Декан",
  },
  // ....
};

const LOCATIONS_ARR = Object.keys(LOCATIONS);

export { LOCATIONS_ARR, LOCATIONS, STATUSES };
