const LOCATIONS = {
  restaurant: "Ресторан",
  spa: "Спа-салон",
  hotel: "Отель",
  terroristBase: "База террористов",
  bank: "Банк",
  hospital: "Больница",
  university: "Университет",
  embassy: "Посольство",
  movieStudio: "Киностудия",
  corporateParty: "Корпоративная вечеринка",
  vegetableMarket: "Овощебаза",
  partisanDetachment: "Партизанский отряд",
  passengerTrain: "Пассажирский поезд",
  pirateShip: "Пиратский корабль",
  polarStation: "Полярная станция",
  supermarket: "Супермаркет",
  theatre: "Театр",
  militaryUnit: "Воинская часть",
  crusaderArmy: "Войско крестоносцев",
  casino: "Казино",
  oceanLiner: "Океанский лайнер",
  orbitalStation: "Орбитальная станция",
  beach: "Пляж",
  submarine: "Подводная лодка",
  policeStation: "Полицейский участок",
  airplane: "Самолёт",
  serviceStations: "Станция техобслуживания",
  church: "Церковь",
  shapitoCircus: "Цирк-шапито",
  school: "Школа",
};

const LOCATIONS_ARR = Object.keys(LOCATIONS);

export { LOCATIONS_ARR, LOCATIONS };
